Updating pipeline

diff --git a/bin/includes/functions b/bin/includes/functions
--- a/bin/includes/functions
+++ b/bin/includes/functions
@@ -20,17 +20,75 @@ minispacer() {
     printf "\n"
 }
 
-spinner() {
-    PID=$!
-    i=1
-    sp="/-\|"
-    echo -n ' '
-    while [ -d /proc/$PID ]
-    do
-        printf "\b${sp:i++%${#sp}:1}"
-        sleep 0.5
-    done
-    printf "\b"
+function _spinner() {
+    # $1 start/stop
+    #
+    # on start: $2 display message
+    # on stop : $2 process exit status
+    #           $3 spinner function pid (supplied from stop_spinner)
+
+    local on_success="DONE"
+    local on_fail="FAIL"
+    local white="\e[1;37m"
+    local green="\e[1;32m"
+    local red="\e[1;31m"
+    local nc="\e[0m"
+
+    case $1 in
+        start)
+            # calculate the column where spinner and status msg will be displayed
+            let column=$(tput cols)-${#2}-8
+            # display message and position the cursor in $column column
+            echo -ne ${2}
+            printf "%${column}s"
+
+            # start spinner
+            i=1
+            sp='\|/-'
+            delay=${SPINNER_DELAY:-0.15}
+
+            while :
+            do
+                printf "\b${sp:i++%${#sp}:1}"
+                sleep $delay
+            done
+            ;;
+        stop)
+            if [[ -z ${3} ]]; then
+                echo "spinner is not running.."
+                exit 1
+            fi
+
+            kill $3 > /dev/null 2>&1
+
+            # inform the user uppon success or failure
+            echo -en "\b["
+            if [[ $2 -eq 0 ]]; then
+                echo -en "${green}${on_success}${nc}"
+            else
+                echo -en "${red}${on_fail}${nc}"
+            fi
+            echo -e "]"
+            ;;
+        *)
+            echo "invalid argument, try {start/stop}"
+            exit 1
+            ;;
+    esac
+}
+
+function start_spinner {
+    # $1 : msg to display
+    _spinner "start" "${1}" &
+    # set global spinner pid
+    _sp_pid=$!
+    disown
+}
+
+function stop_spinner {
+    # $1 : command exit status
+    _spinner "stop" $1 $_sp_pid
+    unset _sp_pid
 }
 
 installer_intro() {
@@ -39,9 +97,6 @@ installer_intro() {
     echo -e "Welcome to the interactive installation process of Jovian"
     echo -e "You are seeing this because one or multiple dependencies of Jovian are missing on your system."
     echo -e "You are using Jovian $VERSION"
-    spacer
-    echo -e "Please keep in mind that this pipeline is still a work-in-progress"
-    echo -e "It is expected that several portions are unstable until release 1.0.0"
     line
     spacer
 }
@@ -73,8 +128,6 @@ ready_for_start() {
     line
     echo -e "All pre-flight checks of Jovian have been completed"
     echo -e "You are using Jovian version ${VERSION}"
-    echo -e "Please keep in mind that this pipeline is still a work-in-progress"
-    echo -e "It is expected that several portions are unstable until release 1.0.0"
     line
     spacer
 }
@@ -93,4 +146,23 @@ parse_yaml() {
          printf("%s%s%s=\"%s\"\n", "'${prefix}'",vn, $2, $3);
       }
    }'
+}
+
+database_part() {
+    local a=$1
+    local n=$2
+    local split="\n"
+    local b=$(spacer)
+    local c=$(thinline)
+    local steps="7"
+    local d="${split}
+    Starting download and installation of the $a database${split}
+    The entire procedure of installing all required databases may require several hours, depending onthe download speed and performance of your computer and/or server.${split}
+    This is step $n of $steps${split}
+    Please stand-by..."
+    echo -e "\e[7m"
+    echo $b
+    echo $c
+    echo -e $d
+    echo -e "\e[0m"
 }
